<?php

namespace app\modules\api\controllers;

class FieldsController extends \yii\rest\ActiveController
{
    public $modelClass = 'app\models\Field';

    public  function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
//        unset($actions['create']);
//        unset($actions['index']);
//        unset($actions['view']);
//        $actions['create'] = [
//            'class' => 'yii\rest\CreateAction',
//            'modelClass' => $this->modelClass,
//            //'checkAccess' => [$this, 'checkAccess'],
//            'scenario' => $this->createScenario,
//        ];
//        $actions['index'] = [
//            'class' => 'yii\rest\IndexAction',
//            'modelClass' => $this->modelClass,
//            //'checkAccess' => [$this, 'checkAccess'],
//        ];
//        $actions['view'] = [
//        'class' => 'yii\rest\ViewAction',
//        'modelClass' => $this->modelClass,
//        'checkAccess' => [$this, 'checkAccess'],
//        ];
        return $actions;
    }
}
